### ISSUE TITLE
How to run the app in Xcode.

### ISSUE THREAD

**Issue by Karthickkck** [priteshrnandgaonkar/react-native-call-detection#1] opened 2017-08-22 04:07 UTC
![screen shot 2017-08-22 at 9 38 25 am](https://user-images.githubusercontent.com/19325688/29548344-acb6d4ee-871d-11e7-9bd6-7a7422087864.png)
i can't find the library in this source.

**Comment by priteshrnandgaonkar** [comment] 2017-08-22 04:46
Did you run `yarn` or `npm install` ? If not run this in the`CallDetectionExample` folder. Will update the README regarding running example. Let me know if this works for you.

**Comment by priteshrnandgaonkar** [comment] 2017-08-22 05:38
<img width="606" alt="screen shot 2017-08-22 at 10 33 29 am" src="https://user-images.githubusercontent.com/3865908/29549350-64d1b88a-8725-11e7-9824-6e826fb63341.png">

You will see the library in `Linked Framework and Libraries` section in the General Tab of Xcode. I have also updated the README regarding how to run the example app.

**Comment by priteshrnandgaonkar** [comment] 2017-08-23 05:08
I hope the issue is resolved, thus closing it. Feel free to reopen the issue if it still exist.

**Closed by priteshrnandgaonkar** 2017-08-23 05:08 UTC
