### ISSUE TITLE
CallDetectionManager cannot be applied to given types;       new CallDetectionManager(), > FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by renege** [priteshrnandgaonkar/react-native-call-detection#63] opened 2020-02-18 15:46 UTC
Why is this not working? I have this package as my only package used in the project:

```
@Override
protected List<ReactPackage> getPackages() {
  @SuppressWarnings("UnnecessaryLocalVariable")
  List<ReactPackage> packages = new PackageList(this).getPackages();
  return packages;
}
```

```
> Task :app:compileReleaseJavaWithJavac FAILED
/Users/hello/Code/_test/foobar/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:78: error: constructor CallDetectionManager in class CallDetectionManager cannot be applied to given types;
      new CallDetectionManager(),
      ^
  required: Application
  found: no arguments
  reason: actual and formal argument lists differ in length
1 error
```

**Comment by wefyns** [comment] 2020-04-13 21:15
I solve this
I think this library don't support react autolinking, because to solve it you need to disable this library in autolinking

create "react-native.config.js" file in your root directory
and past this code
// react-native.config.js
```
module.exports = {
    dependencies: {
      'react-native-call-detection': {
        platforms: {
          android: null, // disable Android platform, other platforms will still autolink if provided
        },
      },
    },
  };
```
then you need link it by command "react-native link react-native-call-detection" (if it dont work use manual link instruction in main page)

one part may different in MainApplication 

```
        @Override
        protected List<ReactPackage> getPackages() {
          @SuppressWarnings("UnnecessaryLocalVariable")
          List<ReactPackage> packages = new PackageList(this).getPackages();
		  packages.add(new CallDetectionManager(MainApplication.this)); // ---> Adding this library
          // Packages that cannot be autolinked yet can be added manually here, for example:
          // packages.add(new MyReactNativePackage());
          return packages;
        }
```

and try to run it, if not working, delete node modules, and run "npm i"
in my case i delete my project and clone it from github again and install it

Worked for me

**Comment by priteshrnandgaonkar** [comment] 2020-04-16 11:22
I have made a new release, and apparently it should fix it, let me know if it doesn't, the issue seems to be duplicate of [this](https://github.com/priteshrnandgaonkar/react-native-call-detection/issues/62)

**Closed by priteshrnandgaonkar** 2020-04-16 11:22 UTC
